### ISSUE TITLE
Burani seliqeye salmag

### ISSUE THREAD

**Issue by asgaraliyev** [TchapApp/mobile-app#153]
![Screenshot_2021-09-21-08-18-48-215_com.tchap.mobile.png](https://user-images.githubusercontent.com/47985813/134111055-66aac1c3-cae8-407f-9693-a4cc564bfd75.png)
Sil nen redakte

**Comment by MamedYahyayev** [comment]
Sil sozunu trash icon ile evez et ve onu yuxari navbarda saga yerlesdir

**Comment by MamedYahyayev** [comment]
![2021-09-23_14-16](https://user-images.githubusercontent.com/66476643/134490781-dccc8908-7674-43a9-aaa2-2d61deb8085f.png)

beyendinizse issue nu close edin
